version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 5
    groups:
      dev-dependencies:
        patterns:
          - '*'
    commit-message:
      prefix: 'chore(deps)'
